export const theme = {
  color: {
    rose: 'var(--color-rose)',
    roseLight: 'var(--color-rose-light)',
    roseLighter: 'var(--color-rose-lighter)',
    roseDark: 'var(--color-rose-dark)',
    sage: 'var(--color-sage)',
    sageLight: 'var(--color-sage-light)',
    sageLighter: 'var(--color-sage-lighter)',
    sageDark: 'var(--color-sage-dark)',
    peri: 'var(--color-peri)',
    periLight: 'var(--color-peri-light)',
    periLighter: 'var(--color-peri-lighter)',
    periDark: 'var(--color-peri-dark)',
    peach: 'var(--color-peach)',
    peachLight: 'var(--color-peach-light)',
    peachLighter: 'var(--color-peach-lighter)',
    powder: 'var(--color-powder)',
    powderLight: 'var(--color-powder-light)',
    powderLighter: 'var(--color-powder-lighter)',
    bg: 'var(--color-bg)',
    bgCard: 'var(--color-bg-card)',
    bgElevated: 'var(--color-bg-elevated)',
    bgInset: 'var(--color-bg-inset)',
    textPrimary: 'var(--color-text-primary)',
    textSecondary: 'var(--color-text-secondary)',
    textMuted: 'var(--color-text-muted)',
    textOnDark: 'var(--color-text-on-dark)',
    success: 'var(--color-success)',
    warning: 'var(--color-warning)',
    danger: 'var(--color-danger)',
    focus: 'var(--color-focus)',
    border: 'var(--color-border)',
    borderStrong: 'var(--color-border-strong)',
  },
  font: {
    display: 'var(--font-display)',
    body: 'var(--font-body)',
    weightRegular: 'var(--font-weight-regular)',
    weightMedium: 'var(--font-weight-medium)',
    weightSemibold: 'var(--font-weight-semibold)',
    weightBold: 'var(--font-weight-bold)',
    sizeXs: 'var(--font-size-xs)',
    sizeSm: 'var(--font-size-sm)',
    sizeMd: 'var(--font-size-md)',
    sizeLg: 'var(--font-size-lg)',
    sizeXl: 'var(--font-size-xl)',
    size2xl: 'var(--font-size-2xl)',
    size3xl: 'var(--font-size-3xl)',
  },
  spacing: {
    xxs: 'var(--spacing-xxs)',
    xs: 'var(--spacing-xs)',
    sm: 'var(--spacing-sm)',
    md: 'var(--spacing-md)',
    lg: 'var(--spacing-lg)',
    xl: 'var(--spacing-xl)',
    '2xl': 'var(--spacing-2xl)',
    '3xl': 'var(--spacing-3xl)',
  },
  radius: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    pill: 'var(--radius-pill)',
  },
  shadow: {
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    xl: 'var(--shadow-xl)',
  },
};
