export const theme = {
  color: {
    brandBayBlue: 'var(--color-brand-bay-blue)',
    brandBerkshiresGreen: 'var(--color-brand-berkshires-green)',
    brandDucklingYellow: 'var(--color-brand-duckling-yellow)',
    brandIndependenceCranberry: 'var(--color-brand-independence-cranberry)',
    brandGraniteGray: 'var(--color-brand-granite-gray)',
    interactiveDefault: 'var(--color-interactive-default)',
    interactiveHover: 'var(--color-interactive-hover)',
    interactiveActive: 'var(--color-interactive-active)',
    interactiveDisabled: 'var(--color-interactive-disabled)',
    interactiveAccentDefault: 'var(--color-interactive-accent-default)',
    interactiveAccentHover: 'var(--color-interactive-accent-hover)',
    interactiveAccentActive: 'var(--color-interactive-accent-active)',
    statusSuccess: 'var(--color-status-success)',
    statusWarning: 'var(--color-status-warning)',
    statusDanger: 'var(--color-status-danger)',
    focus: 'var(--color-focus)',
    white: 'var(--color-neutral-white)',
    black: 'var(--color-neutral-black)',
  },
  font: {
    family: 'var(--font-family-primary)',
    weightRegular: 'var(--font-weight-regular)',
    weightSemibold: 'var(--font-weight-semibold)',
    sizeXs: 'var(--font-size-xs)',
    sizeSm: 'var(--font-size-sm)',
    sizeMd: 'var(--font-size-md)',
    sizeLg: 'var(--font-size-lg)',
    sizeXl: 'var(--font-size-xl)',
    size2xl: 'var(--font-size-2xl)',
    size3xl: 'var(--font-size-3xl)',
    size4xl: 'var(--font-size-4xl)',
    size5xl: 'var(--font-size-5xl)',
    lineHeightBody: 'var(--line-height-body)',
    lineHeightHeading: 'var(--line-height-heading)',
  },
  spacing: {
    xxs: 'var(--spacing-xxs)',
    xs: 'var(--spacing-xs)',
    sm: 'var(--spacing-sm)',
    md: 'var(--spacing-md)',
    lg: 'var(--spacing-lg)',
    xl: 'var(--spacing-xl)',
    '2xl': 'var(--spacing-2xl)',
    '3xl': 'var(--spacing-3xl)',
    '4xl': 'var(--spacing-4xl)',
    '5xl': 'var(--spacing-5xl)',
  },
  radius: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
  },
  shadow: {
    low: 'var(--shadow-low)',
    medium: 'var(--shadow-medium)',
    high: 'var(--shadow-high)',
  },
};
